//base de datos de productos

let stockProductos = [
    {
        id: 1,
        nombre: "Remera Avant",
        tipo: "remera", 
        cantidad: 1, 
        precio: 3000, 
        talle: "L",
        img: '../img/reme1.png',
    },
    {
        id: 2,
        nombre: "Remera Escarabajo",
        tipo: "remera", 
        cantidad: 1, 
        precio: 3000, 
        talle: "L",
        img: '../img/reme2.png',
    },
    {
        id: 3,
        nombre: "Remera Espejo",
        tipo: "remera", 
        cantidad: 1, 
        precio: 3000, 
        talle: "L",
        img: '../img/reme3.png',
    },
    {
        id: 4,
        nombre: "Remera Chiru",
        tipo: "remera", 
        cantidad: 1, 
        precio: 3000, 
        talle: "L",
        img: '../img/reme4.png',
    },
    {
        id: 5,
        nombre: "Remera Estampa",
        tipo: "remera", 
        cantidad: 1, 
        precio: 3000, 
        talle: "L",
        img: '../img/reme5.png',
    },
    {
        id: 6,
        nombre: "Remera Astromutante",
        tipo: "remera", 
        cantidad: 1, 
        precio: 3000, 
        talle: "L",
        img: '../img/reme6.png',
    },
    {
        id: 7,
        nombre: "Remera Cuánto",
        tipo: "remera", 
        cantidad: 1, 
        precio: 3000, 
        talle: "L",
        img: '../img/reme7.png',
    },
    {
        id: 8,
        nombre: "Remera Field",
        tipo: "remera", 
        cantidad: 1, 
        precio: 3000, 
        talle: "L",
        img: '../img/reme8.png',
    },
    {
        id: 9,
        nombre: "Remera Dentadura",
        tipo: "remera", 
        cantidad: 1, 
        precio: 3000, 
        talle: "L",
        img: '../img/reme9.png',
    }
]